name: Conditions
on: push
jobs:
   conditions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${FORMAT_RUNID}
        env: 
          FORMAT_RUNID: ${{ format('run_id:{0}', github.run_id) }}
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}

