name: Override environment variables
on: push
env: 
  EXAMPLE: Defined by workflow level
jobs:
  print:
    runs-on: windows-latest  
    steps:
      - run: echo $env:EXAMPLE
      - env:
          EXAMPLE: Defined by step level
        run: echo $env:EXAMPLE
      

