name: Hash functions
on: 
  push:
jobs:
  hash_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
      - run: echo ${{ contains(github.run_id, '1' }}


