name: Secrets
on: push
jobs:
  print:
    runs-on: windows-latest  
    env:
      PASSWORD: ${{ secrets.PASSWORD_A }}
    steps:
      - run: echo $env:PASSWORD
      - run: echo $env:PASSWORD[0]
      

